// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/CompressorRun.h"
#include "Commands/Drive.h"
#include "Commands/ShifterHigh.h"
#include "Commands/ShifterLow.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	shooterJoystick = new Joystick(2);
	
	driverJoystick = new Joystick(1);
	
	shiftLowButton = new JoystickButton(driverJoystick, 2);
	shiftLowButton->WhenPressed(new ShifterLow());
	shiftHighButton = new JoystickButton(driverJoystick, 1);
	shiftHighButton->WhenPressed(new ShifterHigh());
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
	SmartDashboard::PutData("Drive", new Drive());
	SmartDashboard::PutData("ShifterHigh", new ShifterHigh());
	SmartDashboard::PutData("ShifterLow", new ShifterLow());
	SmartDashboard::PutData("CompressorRun", new CompressorRun());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getShooterJoystick() {
	return shooterJoystick;
}
Joystick* OI::getDriverJoystick() {
	return driverJoystick;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
