// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/ClockspringsTensionHigh.h"
#include "Commands/ClockspringsTensionLow.h"
#include "Commands/CompressorRun.h"
#include "Commands/Drive.h"
#include "Commands/PickWheelsReverseFast.h"
#include "Commands/PickupArmsExtend.h"
#include "Commands/PickupArmsMidwayHi.h"
#include "Commands/PickupArmsMidwayLo.h"
#include "Commands/PickupArmsRetract.h"
#include "Commands/PickupWheelsForward.h"
#include "Commands/PickupWheelsOff.h"
#include "Commands/PickupWheelsReverseSlow.h"
#include "Commands/ShifterHigh.h"
#include "Commands/ShifterLow.h"
#include "Commands/ThrowerShoot.h"
#include "Commands/ThrowerUp.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	rightJoystick = new Joystick(2);
	
	shiftLowButton = new JoystickButton(rightJoystick, 3);
	shiftLowButton->WhenPressed(new ShifterLow());
	leftJoystick = new Joystick(1);
	
	shiftHighButton = new JoystickButton(leftJoystick, 3);
	shiftHighButton->WhenPressed(new ShifterHigh());
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
	SmartDashboard::PutData("Drive", new Drive());
	SmartDashboard::PutData("ShifterHigh", new ShifterHigh());
	SmartDashboard::PutData("ShifterLow", new ShifterLow());
	SmartDashboard::PutData("CompressorRun", new CompressorRun());
	SmartDashboard::PutData("PickupWheelsOff", new PickupWheelsOff());
	SmartDashboard::PutData("PickupWheelsForward", new PickupWheelsForward());
	SmartDashboard::PutData("PickupWheelsReverseSlow", new PickupWheelsReverseSlow());
	SmartDashboard::PutData("PickWheelsReverseFast", new PickWheelsReverseFast());
	SmartDashboard::PutData("ClockspringsTensionLow", new ClockspringsTensionLow());
	SmartDashboard::PutData("ClockspringsTensionHigh", new ClockspringsTensionHigh());
	SmartDashboard::PutData("Pickup Arms Extend", new PickupArmsExtend());
	SmartDashboard::PutData("Pickup Arms Retract", new PickupArmsRetract());
	SmartDashboard::PutData("Pickup Arms Midway Hi", new PickupArmsMidwayHi());
	SmartDashboard::PutData("Thrower Shoot", new ThrowerShoot());
	SmartDashboard::PutData("Thrower Up", new ThrowerUp());
	SmartDashboard::PutData("Pickup Arms Midway Lo", new PickupArmsMidwayLo());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	leftXboxController = new Object360(1);
	rightXboxController = new Object360(2);
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getRightJoystick() {
	return rightJoystick;
}
Joystick* OI::getLeftJoystick() {
	return leftJoystick;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
	Object360* OI::getLeftController()
	{
		return leftXboxController;
	}
	
	Object360* OI::getRightController()
	{
		return rightXboxController;
	}
