// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "CheckHot.h"

CheckHot::CheckHot() :
myRobot(1, 2),	// these must be initialized in the same order
stick(1)		// as they are declared above.
{
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::vision);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	myRobot.SetExpiration(0.1);
	myRobot.SetSafetyEnabled(false);
}

// Called just before this Command runs the first time
void CheckHot::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void CheckHot::Execute() {
	
}

// Make this return true when this Command no longer needs to run execute()
bool CheckHot::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void CheckHot::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void CheckHot::Interrupted() {
	End();
}
