// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "DriveNFeet.h"
DriveNFeet::DriveNFeet(float distance) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	_distance = distance;
	controller = new PIDController(.8,.0,0, Robot::driveTrain, Robot::driveTrain);
	controller->SetTolerance(.1);
}
// Called just before this Command runs the first time
void DriveNFeet::Initialize() 
{
	Robot::driveTrain->ResetEncoders();
	Robot::driveTrain->Set(0);
	controller->SetSetpoint(_distance);
	controller->Enable();
}
// Called repeatedly when this Command is scheduled to run
void DriveNFeet::Execute() {
	
}
// Make this return true when this Command no longer needs to run execute()
bool DriveNFeet::IsFinished() {
	return controller->OnTarget();
}
// Called once after isFinished returns true
void DriveNFeet::End() {
	Robot::driveTrain->Set(0);
	controller->Disable();
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveNFeet::Interrupted() {
	End();
}
