// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#ifndef DRIVENFEET_H
#define DRIVENFEET_H


#include "Commands/Subsystem.h"
#include "../Robot.h"


const float DRIVENFEET_PID_P = .075;
const float DRIVENFEET_PID_I = .0;
const float DRIVENFEET_PID_D = .1;
const float DRIVENFEET_PID_TOLERANCE = .1;

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveNFeet: public Command {
public:
	DriveNFeet(float);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
private:
	float _distance;
	PIDController *controller;
	
};

#endif
