// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#ifndef DRIVEUNTILXFEET_H
#define DRIVEUNTILXFEET_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

const float DRIVEUNTILXFEET_PID_P = .33;
const float DRIVEUNTILXFEET_PID_I = .0;
const float DRIVEUNTILXFEET_PID_D = .0008;
const float DRIVEUNTILXFEET_PID_TOLERANCE = .05;
/**
 *
 *
 * @author ExampleAuthor
 */
class DriveUntilXFeet: public Command {
public:
	DriveUntilXFeet(float);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
private:
	float _distance;
	PIDController *controller;
	
};

#endif
