// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.




#include "PickupWheels.h"
#include "../Robotmap.h"
#include "../Commands/PickupWheelsOff.h"
#include "../Commands/PickupWheelsForward.h"
#include "../Commands/PickupWheelsReverseSlow.h"
#include "../Commands/PickupWheelsReverseFast.h"


PickupWheels::PickupWheels() : Subsystem("PickupWheels") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	rightPickupWheel = RobotMap::pickupWheelsRightPickupWheel;
	leftPickupWheel = RobotMap::pickupWheelsLeftPickupWheel;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void PickupWheels::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.
void PickupWheels::SetOff()
{
	rightPickupWheel->Set(0);
	leftPickupWheel->Set(0);
}

void PickupWheels::SetForward()
{
	rightPickupWheel->Set(.6);
	leftPickupWheel->Set(-.6);
}

void PickupWheels::SetReverseSlow()
{
	rightPickupWheel->Set(-.3);
	leftPickupWheel->Set(0.3);
}

void PickupWheels::SetReverseFast()
{
	rightPickupWheel->Set(-.6);
	leftPickupWheel->Set(.6);
}

void PickupWheels::SetSpeed(float speed)
{
	rightPickupWheel->Set(speed);
	leftPickupWheel->Set(-speed);
}
