// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Shifter.h"
#include "../Robotmap.h"
#include "../Commands/ShifterHigh.h"
#include "../Commands/ShifterLow.h"

#include "SmartDashboard/SmartDashboard.h"

bool shifterIsHigh = true;
bool timing = false;

Shifter::Shifter() : Subsystem("Shifter") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	shifterLeft = RobotMap::shifterShifterLeft;
	shifterRight = RobotMap::shifterShifterRight;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	shiftTimer = new Timer();
}
    
void Shifter::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
//	SetDefaultCommand(new ShifterHigh());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
void Shifter::ShiftHigh()
{
	shifterLeft->Set(DoubleSolenoid::kReverse);
	shifterRight->Set(DoubleSolenoid::kReverse);
		
	SmartDashboard::PutBoolean("Shifted High", true);
	SmartDashboard::PutBoolean("Shifted Low", false);
}
void Shifter::ShiftLow()
{
	shifterLeft->Set(DoubleSolenoid::kForward);
	shifterRight->Set(DoubleSolenoid::kForward);
		
	SmartDashboard::PutBoolean("Shifted High", false);
	SmartDashboard::PutBoolean("Shifted Low", true);
}
void Shifter::ShiftOff()
{
	shifterLeft->Set(DoubleSolenoid::kOff);
	shifterRight->Set(DoubleSolenoid::kOff);
	
	SmartDashboard::PutBoolean("Shifted High", false);
	SmartDashboard::PutBoolean("Shifted Low", false);
}
